config:
  categories:
  - web
  - forensics
  - crypto
  - misc
  - re
  - pwn
  - osint
  difficulties:
  - name: easy
    value: 500
  - name: medium
    value: 500
  - name: hard
    value: 500
  port: 8000
  name: GCTF