config:
  categories:
  - web
  - forensics
  - crypto
  - misc
  - re
  - pwn
  - osint
  difficulties:
  - name: easy
    value: 500
  - name: medium
    value: 500
  - name: hard
    value: 500
  name: GCTF
  port: 5000
  port_mappings:
    NextJS Timeless:
      from_port: '3000'
      to_port: '5003'
    bulls-dream:
      from_port: '1337'
      to_port: '5000'
    double_protection:
      from_port: '1337'
      to_port: '6000'
    droid-toolbox-server:
      from_port: '10083'
      to_port: '7000'
    knockoff-pastebin:
      from_port: '1337'
      to_port: '5001'
    knockoff-pastebin-2:
      from_port: '1337'
      to_port: '5002'
    math-server-1:
      from_port: '1337'
      to_port: '7001'
    number-guessr-1:
      from_port: '1337'
      to_port: '5004'
    number-guessr-2:
      from_port: '1337'
      to_port: '5005'
    number-guessr-3:
      from_port: '1337'
      to_port: '5006'
    password-server-1:
      from_port: '1337'
      to_port: '7002'
    take_it_down:
      from_port: '1337'
      to_port: '8000'
